database:
  connection:
    host: "localhost"
    port: 27017
    username: ""  # Non servono autenticazione
    password: ""  
  settings:
    name: "SmartPlant"  # Nome del database
    auth_source: "admin"